---
title: "beginning"
format: pdf
---

```{r}
quadratic_function_solve <- function(a,b,c){
  delta <- b^2 - 4 * a * c
  if(delta > 0){
    root1 <- (-b + sqrt(delta)) / (2 * a)
    root2 <- (-b - sqrt(delta)) / (2 * a)
    return(c(root1,root2))
  }else if(delta == 0){
    return((-b) / (2 * a))
  }else{
    return("no real solutions")
  }
}
a <- 1
b <- -1
c <- -2
result <- quadratic_function_solve(a,b,c)
result
```

```{r}
x <- seq(-5, 5, length = 100)
f <- a * x^2 + b * x + c
a <- 1
b <- -1
c <- -2
plot(x, f, type="l")
lines(x)
```

```{r}
coefs1 <- scan("../../data/coefs1.txt")
a <- coefs1[1]
b <- coefs1[2]
c <- coefs1[3]
result1 <- quadratic_function_solve(a,b,c)
result1
```

```{r}
for (i in 1:3){
  file.create(paste0("../../results/results", i, ".txt"))
  coefs <- scan(paste0("../../data/coefs",i,".txt"))
  a <- coefs[1]
  b <- coefs[2]
  c <- coefs[3]
  result <- quadratic_function_solve(a,b,c)
  write(result,file = paste0("../../results/results", i, ".txt"))
}
```
